
language: c
sudo: false

git:
  submodules: false

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

compiler:
  - gcc

python:
  - "2.6"

addons:
  postgresql: "9.2"

services:
  - postgresql

## ----------------------------------------------------------------------
## Install supporting Python modules
## ----------------------------------------------------------------------

install:
  - pip install --user setuptools

before_script:
  - export PATH=${TRAVIS_BUILD_DIR}/tools/bin:$PATH

## ----------------------------------------------------------------------
## Perform build:
## ----------------------------------------------------------------------

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install

## ----------------------------------------------------------------------
## Notification
## ----------------------------------------------------------------------

notifications:
  email:
    recipients:
      - sramanujam@pivotal.io
    on_success: change
    on_failure: always
