
language: c
sudo: true

git:
  submodules: false

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

compiler:
  - gcc

python:
  - "2.6"

addons:
  postgresql: "9.2"
  artifacts: true

services:
  - postgresql

## ----------------------------------------------------------------------
## Install dependencies
## ----------------------------------------------------------------------

install:
  - pip install --user setuptools
  - mkdir -p ${TRAVIS_BUILD_DIR}/tools
  - cd ${TRAVIS_BUILD_DIR}/tools
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get -y update
  - sudo apt-get -y install texlive
  - sudo apt-get install postgresql-server-9.4
  - sudo apt-get install postgresql-server-dev-9.4
  - sudo apt-get install postgresql-client
  - wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.linux.bin.tar.gz
  - tar -zxvf doxygen-1.8.4.linux.bin.tar.gz -C ${TRAVIS_BUILD_DIR}/tools
  - sudo apt-get install -y rpm

before_script:
  - export PATH=${TRAVIS_BUILD_DIR}/tools/bin:${TRAVIS_BUILD_DIR}/tools/doxygen-1.8.4/bin:$PATH

## ----------------------------------------------------------------------
## Build
## ----------------------------------------------------------------------

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make package
  - make gppkg
  - make doc

## ----------------------------------------------------------------------
## Notify
## ----------------------------------------------------------------------

notifications:
  email:
    recipients:
      - sramanujam@pivotal.io
    on_success: change
    on_failure: always
