language: c
sudo: true
git:
  submodules: false
compiler:
- gcc
python:
- '2.6'
addons:
  postgresql: '9.2'
  artifacts: true
services:
- postgresql
install:
- pip install --user setuptools
- mkdir -p ${TRAVIS_BUILD_DIR}/tools
- cd ${TRAVIS_BUILD_DIR}/tools
- sudo add-apt-repository -y ppa:texlive-backports/ppa
- sudo apt-get -y update
- sudo apt-get -y install texlive-full
- sudo apt-get -y install texlive
#- sudo apt-get install texlive-latex-extra
#- sudo apt-get install texlive-bibtex-extra
- sudo apt-get install postgresql-9.2 postgresql-client-9.2
- sudo apt-get install postgresql-server-dev-9.2
- wget http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.4.linux.bin.tar.gz
- tar -zxvf doxygen-1.8.4.linux.bin.tar.gz -C ${TRAVIS_BUILD_DIR}/tools
- sudo apt-get install -y rpm
before_script:
- export PATH=${TRAVIS_BUILD_DIR}/tools/bin:${TRAVIS_BUILD_DIR}/tools/doxygen-1.8.4/bin:$PATH
script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- cd build
- cmake ..
- make
- make package
- make gppkg
- make doc
- cd ${TRAVIS_BUILD_DIR}/doc/user/latex
- make pdf
notifications:
  email:
    recipients:
    - sramanujam@pivotal.io
    on_success: change
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: Po9n/WIdjJSIdLkvOIVR97b2piigz6y/z7j19FdqVY6LSi0yDrW+7edOyt0sP/lgHu7roCsFEZO0dRiHu5rD5f5/3uStGL5bvN8hZ05NWQzzJSNt0K8yo/zBHZpL9WeDa5dUupM7WXUmLt20Ggt4J4yBQhVQWhSvhDbiXgvUXcLKiUAwyimOcpaQkOnOb0WWyUZgx/LQVxc9FxUCPArxbYVjHBYr2B/W0zYo9QW3jcpLLQ2ld+2LakRhb5TDBZCRK1vlHIpmq3TZoddCfhaauDJkTIpXc4g3h8UaPD48iyiHHTv98AwhnY/PuiABGfPu9He6D48DPoKHoUNbLWcY62kIA3gnOfPpZn7XaoaGswgswNrvhKANCAdjki7vZu2CubN1Fc2csJ0FfJ+7XMKDXSk2jAPB6XyVtUdvmU7WTgYZ0cxFI9NZrJP3loK6rV07ULfTLviabTrTs01MMZOG3hxQ8NHNXPm0ntXyxftUECjyEYfKl4pb4J3L7VyOrJK6Il92bPg9ruRrdLYoPSG5tpefFNHRs4mA5RBAq6Jt7XYXabgd0RmPPV+S51VGw8rcFmMOdQcpOl+T0uCDLte9VtP+EKF0BYRMQiHz1BsSZ5DmpWeKHwRGuNbwvkpyjHzARfsVobkFi9Gp68dOVQImJ4q948MWvEU/Kvo5+BTPehg=
  file: 
    - madlib-1.8dev-Linux.rpm
    - doc/user/latex/refman.pdf
  on:
    repo: vatsan/incubator-madlib
    tags: true
  skip_cleanup: true
