
language: c
sudo: true

git:
  submodules: false

## ----------------------------------------------------------------------
## Build tools
## ----------------------------------------------------------------------

compiler:
  - gcc

python:
  - "2.6"

addons:
  postgresql: "9.2"

services:
  - postgresql

## ----------------------------------------------------------------------
## Install dependencies
## ----------------------------------------------------------------------

install:
  - pip install --user setuptools
  - sudo apt-get install texlive-full
  - sudo apt-get install doxygen

before_script:
  - export PATH=${TRAVIS_BUILD_DIR}/tools/bin:$PATH

## ----------------------------------------------------------------------
## Build
## ----------------------------------------------------------------------

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make package
  - make gppkg
  - make doc
  - cd doc/user/latex
  - make pdf

## ----------------------------------------------------------------------
## Notify
## ----------------------------------------------------------------------

notifications:
  email:
    recipients:
      - sramanujam@pivotal.io
    on_success: change
    on_failure: always
